//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIC_EVO_Dashboard.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIC_EVO_Dashboard.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALVE POSITION ERROR.
        /// </summary>
        public static string ErrorCode1 {
            get {
                return ResourceManager.GetString("ErrorCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL ERROR DUE TO UPSTREAM SENSOR PRESSURE DIFFERENCE.
        /// </summary>
        public static string ErrorCode10 {
            get {
                return ResourceManager.GetString("ErrorCode10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL ERROR DUE TO DOWNSTREAM SENSOR PRESSURE DIFFERENCE.
        /// </summary>
        public static string ErrorCode11 {
            get {
                return ResourceManager.GetString("ErrorCode11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOSS OF  FLOW DEMAND.
        /// </summary>
        public static string ErrorCode2 {
            get {
                return ResourceManager.GetString("ErrorCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT1000 SENSOR FAILURE.
        /// </summary>
        public static string ErrorCode3 {
            get {
                return ResourceManager.GetString("ErrorCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1 OUT OF RANGE.
        /// </summary>
        public static string ErrorCode4 {
            get {
                return ResourceManager.GetString("ErrorCode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2 OUT OF RANGE.
        /// </summary>
        public static string ErrorCode5 {
            get {
                return ResourceManager.GetString("ErrorCode5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P3 OUT OF RANGE.
        /// </summary>
        public static string ErrorCode6 {
            get {
                return ResourceManager.GetString("ErrorCode6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P4 OUT OF RANGE.
        /// </summary>
        public static string ErrorCode7 {
            get {
                return ResourceManager.GetString("ErrorCode7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPSTREAM PRESSURE DIFFERENTIAL ALARM.
        /// </summary>
        public static string ErrorCode8 {
            get {
                return ResourceManager.GetString("ErrorCode8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNSTREAM PRESSURE DIFFERENTIAL ALARM.
        /// </summary>
        public static string ErrorCode9 {
            get {
                return ResourceManager.GetString("ErrorCode9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR CODES.
        /// </summary>
        public static string ErrorCodeTitle {
            get {
                return ResourceManager.GetString("ErrorCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLOW ALGORITHM.
        /// </summary>
        public static string FlowAlgorithm {
            get {
                return ResourceManager.GetString("FlowAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLOW DEMAND (4-20mA).
        /// </summary>
        public static string FlowTitle {
            get {
                return ResourceManager.GetString("FlowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUEL TEMPERATURE (°C/°F).
        /// </summary>
        public static string FuelTempTitle {
            get {
                return ResourceManager.GetString("FuelTempTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1 UPSTREAM.
        /// </summary>
        public static string P1Title {
            get {
                return ResourceManager.GetString("P1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2 UPSTREAM.
        /// </summary>
        public static string P2Title {
            get {
                return ResourceManager.GetString("P2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P3 DOWNSTREAM.
        /// </summary>
        public static string P3Title {
            get {
                return ResourceManager.GetString("P3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P4 DOWNSTREAM.
        /// </summary>
        public static string P4Title {
            get {
                return ResourceManager.GetString("P4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one....
        /// </summary>
        public static string Picker {
            get {
                return ResourceManager.GetString("Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALVE POSITION (%).
        /// </summary>
        public static string PositionTitle {
            get {
                return ResourceManager.GetString("PositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string UnitTitle {
            get {
                return ResourceManager.GetString("UnitTitle", resourceCulture);
            }
        }
    }
}
